language: php

sudo: required

php:
  - 7.1
  - 7.2

dist: trusty

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

#script:
#  - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml

install:
  - composer install

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS lida;'
  - php artisan migrate:refresh --seed
  - php artisan serve &

env:
  global:
    - APP_NAME=Lida
    - APP_ENV=local
    - APP_KEY=base64:s2D8Wl+t5T7Wnm2RBY9AQSY7Ow/e2aBIAqkdhny1Trk=
    - APP_DEBUG=true
    - APP_URL=http://127.0.0.1:8000

    - LOG_CHANNEL=stack
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=lida
    - DB_USERNAME=root
    - DB_PASSWORD=
    - DB_PREFIX=lr_

    - BROADCAST_DRIVER=log
    - CACHE_DRIVER=database
    - SESSION_DRIVER=database
    - SESSION_LIFETIME=200
    - QUEUE_DRIVER=database

    - REDIS_HOST=127.0.0.1
    - REDIS_PASSWORD=null
    - REDIS_PORT=6379

    - MAIL_DRIVER=ses
    - MAIL_HOST=smtp.mailtrap.io
    - MAIL_PORT=2525
    - MAIL_USERNAME=null
    - MAIL_PASSWORD=null
    - MAIL_ENCRYPTION=null

    - PUSHER_APP_ID=
    - PUSHER_APP_KEY=
    - PUSHER_APP_SECRET=
    - PUSHER_APP_CLUSTER=mt1

    - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

    - SETTING_STORE=json